### PR TITLE
Fix missing introspection for record accessors

### LINKED ISSUE #3539: Property introspection not able to identify record accessors
* assertj core version: 3.26.3
* java version: 21
* test framework version: junit-jupiter-api 5.9.3

**Test case reproducing the bug**

```java
    private record DummyRecord(String name, int revision) {

        //This is the culprit, as the naming seems to affect assertJ's internal reflection-logic. Comparison works as expected when I rename this method to anything different. 
        public boolean isRevision() {
            return revision != 1;
        }
    }

    @Test public void recursiveComparison_javaRecords() {
        assertThat(new DummyRecord("Bob", 10)).usingRecursiveComparison().isEqualTo(new DummyRecord("Bob", 2)); //passes, but should fail
    }
```

### PR DESCRIPTION
**Pull request by scordio**
* Fixes #3539

### CODE REVIEW

**Comment by scordio** [comment]
Setting as draft as I'll simplify the test case a bit further.

File: assertj-tests/assertj-integration-tests/assertj-core-tests/src/test/java/org/assertj/tests/core/api/recursive/comparison/RecursiveComparisonAssert_isNotEqualTo_with_record_Test.java [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+  // https://github.com/assertj/assertj/issues/3539
+  @Test
+  void should_compare_records_with_component_named_as_boolean_accessor() {
+    // GIVEN
+    record Record(String field, boolean isField) {
+    }
+    Record actual = new Record("value1", true);
+    Record other = new Record("value2", true);
+    // WHEN/THEN
+    assertThat(actual).usingRecursiveComparison().isNotEqualTo(other);
```
Comment (joel-costigliola) [inline assertj-tests/assertj-integration-tests/assertj-core-tests/src/test/java/org/assertj/tests/core/api/recursive/comparison/RecursiveComparisonAssert_isNotEqualTo_with_record_Test.java:30]: use `then` as per the contribution guidelines :laughing:
